services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - "./backend/.env"
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
      - ./backend/tsconfig.json:/app/tsconfig.json
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: konfigo
      POSTGRES_PASSWORD: super_secure_password
      POSTGRES_DB: konfigo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer:
    image: adminer
    ports:
      - "8080:8080"
